added - score, scoreDto, scoreMapper
Project-web-2018-01/kodigames-backend-java pull request #5
Opened 2018-02-23 20:08 UTC by Maciolek

2018-02-23 21:41 UTC, paulinakuzmicka commented on src/main/java/com/kodigames/domain/Score.java
> +@Table(name = "SCORE")
SCORES

2018-02-23 21:43 UTC, Maciolek commented on src/main/java/com/kodigames/domain/Score.java
> +    private long gameId;
id

2018-02-25 20:39 UTC, maciolek commented on src/main/java/com/kodigames/domain/ScoreDto.java
> +    private long gameId;
id

2018-02-25 20:39 UTC, maciolek commented on src/main/java/com/kodigames/domain/Score.java
> +
game_id i user_Id do wycięcia

2018-03-02 20:14 UTC, paulinakuzmicka approved these changes
Now is ok :)

2018-03-02 21:50 UTC, paulinakuzmicka requested changes

2018-03-02 21:50 UTC, paulinakuzmicka commented on src/main/java/com/kodigames/domain/Score.java
> +    private int score;
Add private long userGameId

2018-03-09 20:37 UTC, paulinakuzmicka approved these changes
Ok :)

2018-03-09 21:50 UTC, merged